[project]
name = "5tmate-nuclei"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-aws>=6.0.0,<7.0.0",
    "pulumi-command>=1.0.0,<2.0.0",
    "pulumi-docker-build>=0.0.10,<1.0.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.11.0",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
